apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template: 
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: mooseelksson/vprofileapp
          ports:
            - name: vproapp-port
              containerPort: 8080
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
      initContainers:
        - name: init-mydb
          image: busybox:latest
          command: ["sh", "-c", "until nslookup vprodb; do echo waiting for mydb; sleep 2; done;"]
        - name: init-memcache
          image: busybox:latest
          command: ["sh", "-c", "until nslookup vprocache01; do echo waiting for memcache; sleep 2; done;"]
